In [3]:
import tensorflow as tf
import numpy as np
import datetime

In [47]:
np.random.seed(1)

In [8]:
print(f"Notebook last run (end-to-end): {datetime.datetime.now()}")

Notebook last run (end-to-end): 2024-03-20 10:47:04.921462


In [9]:
print(tf.__version__)

2.15.0


In [14]:
scaler = tf.constant(10)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [16]:
scaler.ndim, scaler.shape

(0, TensorShape([]))

In [17]:
vector = tf.constant([2,5])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 5])>

In [19]:
vector.ndim, vector.shape

(1, TensorShape([2]))

In [26]:
matrix = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
matrix.dtype

tf.float32

In [27]:
matrix

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [22]:
matrix.ndim, matrix.shape

(2, TensorShape([2, 2]))

In [28]:
another_matrix = tf.constant([
    [1.0, 2.0],
    [3.0, 4.0],
    [5.0, 6.0]
], dtype=tf.float16)

another_matrix.dtype

tf.float16

In [30]:
another_matrix.ndim, another_matrix.shape

(2, TensorShape([3, 2]))

In [58]:
rndValues = np.random.randn(100, 3, 2)

In [59]:
res = tf.constant(rndValues)

In [62]:
res.shape 

TensorShape([100, 3, 2])

In [63]:
res.ndim

3

In [67]:
changeable_tensor = tf.Variable([10, 5])
unchangeable_tensor = tf.constant([10, 5])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  5])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  5])>)

In [71]:
changeable_tensor[0].assign(3)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([3, 5])>

In [72]:
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 5])>

In [76]:
#unchangeable_tensor[0].assign(50)

#### Creating random tensors


In [95]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))
random_1 , random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [97]:
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
shuffled = tf.random.shuffle(not_shuffled)

In [98]:
not_shuffled, shuffled

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4],
        [ 2,  5]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 2,  5],
        [ 3,  4],
        [10,  7]])>)

In [101]:
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]])>

In [105]:
tf.random.uniform(shape=(10, 5), minval=10, maxval=100, seed=42, dtype=tf.float32)

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[78.54261 , 43.45498 , 39.939247, 77.78501 , 78.65807 ],
       [61.20102 , 96.16909 , 18.339674, 43.427868, 54.593464],
       [86.70108 , 66.50231 , 58.07484 , 76.687744, 38.144463],
       [48.10109 , 68.84221 , 69.3244  , 71.10289 , 26.238962],
       [68.71461 , 49.82866 , 37.671654, 74.084   , 64.47735 ],
       [43.95284 , 33.01731 , 66.93768 , 93.01724 , 48.73804 ],
       [93.98853 , 81.868805, 62.259926, 38.015053, 59.961056],
       [30.560946, 13.137069, 85.38284 , 62.923386, 21.550901],
       [28.058197, 53.470627, 64.88353 , 22.97158 , 55.397366],
       [93.83836 , 30.57103 , 97.65029 , 56.73155 , 97.729294]],
      dtype=float32)>

#### Anothe Ways To Make Tensors

In [110]:
tf.zeros(shape = (5, 3)), tf.ones(shape = (5, 3))

(<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(5, 3), dtype=float32, numpy=
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=float32)>)

In [116]:
tf.eye(num_rows=5, num_columns=5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [121]:
numpy_A = np.arange(1, 25,)
tf.constant(numpy_A, dtype=tf.float32, shape=[2, 4, 3])

<tf.Tensor: shape=(2, 4, 3), dtype=float32, numpy=
array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]],

       [[13., 14., 15.],
        [16., 17., 18.],
        [19., 20., 21.],
        [22., 23., 24.]]], dtype=float32)>

#### <span style='color:#080'> Get Information From tensor </span>

In [124]:
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [125]:
 rank_4_tensor.ndim

4

In [126]:
tf.size( rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [128]:
rank_4_tensor.shape[-1]

5

In [130]:
m, w, h, c = rank_4_tensor.shape

In [132]:
m, w, h, c

(2, 3, 4, 5)

#### Slicing

In [141]:
t = tf.random.normal(shape=(2, 3, 3))

In [142]:
t

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[-0.35975078,  1.5145855 ,  0.9998955 ],
        [-0.83270323,  0.10627943, -1.6242576 ],
        [ 1.5322537 , -0.63025033,  0.17648193]],

       [[ 0.19940554, -0.31985644,  0.20605735],
        [-0.38278538, -0.97199893, -0.33949786],
        [ 1.0419518 , -0.37069583, -0.91420484]]], dtype=float32)>

In [154]:
t[:, :, :1]

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[-0.35975078],
        [-0.83270323],
        [ 1.5322537 ]],

       [[ 0.19940554],
        [-0.38278538],
        [ 1.0419518 ]]], dtype=float32)>

In [160]:
tnewaxis = t[..., tf.newaxis]

In [165]:
tnewaxis[..., tf.newaxis]

<tf.Tensor: shape=(2, 3, 3, 1, 1), dtype=float32, numpy=
array([[[[[-0.35975078]],

         [[ 1.5145855 ]],

         [[ 0.9998955 ]]],


        [[[-0.83270323]],

         [[ 0.10627943]],

         [[-1.6242576 ]]],


        [[[ 1.5322537 ]],

         [[-0.63025033]],

         [[ 0.17648193]]]],



       [[[[ 0.19940554]],

         [[-0.31985644]],

         [[ 0.20605735]]],


        [[[-0.38278538]],

         [[-0.97199893]],

         [[-0.33949786]]],


        [[[ 1.0419518 ]],

         [[-0.37069583]],

         [[-0.91420484]]]]], dtype=float32)>

In [167]:
t.shape

TensorShape([2, 3, 3])

#### New Axis At The End Of Tensor

In [171]:
tf.expand_dims(t, axis=-1) , t[..., tf.newaxis]

(<tf.Tensor: shape=(2, 3, 3, 1), dtype=float32, numpy=
 array([[[[-0.35975078],
          [ 1.5145855 ],
          [ 0.9998955 ]],
 
         [[-0.83270323],
          [ 0.10627943],
          [-1.6242576 ]],
 
         [[ 1.5322537 ],
          [-0.63025033],
          [ 0.17648193]]],
 
 
        [[[ 0.19940554],
          [-0.31985644],
          [ 0.20605735]],
 
         [[-0.38278538],
          [-0.97199893],
          [-0.33949786]],
 
         [[ 1.0419518 ],
          [-0.37069583],
          [-0.91420484]]]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3, 3, 1), dtype=float32, numpy=
 array([[[[-0.35975078],
          [ 1.5145855 ],
          [ 0.9998955 ]],
 
         [[-0.83270323],
          [ 0.10627943],
          [-1.6242576 ]],
 
         [[ 1.5322537 ],
          [-0.63025033],
          [ 0.17648193]]],
 
 
        [[[ 0.19940554],
          [-0.31985644],
          [ 0.20605735]],
 
         [[-0.38278538],
          [-0.97199893],
          [-0.33949786]],
 
         

In [170]:
tf.expand_dims(t, axis=-1).shape , t[..., tf.newaxis].shape

(TensorShape([2, 3, 3, 1]), TensorShape([2, 3, 3, 1]))

#### Manipulating tensors (tensor operations)


In [172]:
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [173]:
tensor - 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  2],
       [-2, -1]])>

In [174]:
tensor * 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 14],
       [ 6,  8]])>

In [177]:
tensor  / 2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [1.5, 2. ]])>

In [178]:
tensor % 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 0]])>

In [179]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [180]:
tf.subtract(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]])>

In [181]:
tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [184]:
tf.divide(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

#### Matrix mutliplication


In [187]:
t1 = tf.constant([[2, 3], [5, 7]])
t2 = tf.constant([[2, 3, 5], [5, 7, 10]])

In [188]:
t1.shape, t2.shape

(TensorShape([2, 2]), TensorShape([2, 3]))

In [189]:
tf.matmul(t1, t2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[19, 27, 40],
       [45, 64, 95]])>

In [190]:
t1 @ t2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[19, 27, 40],
       [45, 64, 95]])>

In [191]:
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

In [192]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [194]:
X.shape, Y.shape

(TensorShape([3, 2]), TensorShape([3, 2]))

In [198]:
tf.transpose(X) @Y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [201]:
tf.matmul(tf.transpose(Y), X)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89, 116],
       [ 98, 128]])>

In [204]:
Y.shape

TensorShape([3, 2])

In [208]:
tf.reshape(tensor=Y, shape=(2, 3)).shape

TensorShape([2, 3])

In [207]:
X.shape

TensorShape([3, 2])

In [206]:
tf.matmul(X, tf.reshape(tensor=Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [209]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [210]:
tf.matmul(a = X, b= Y, transpose_a = True, transpose_b = False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [211]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [214]:
tf.tensordot(a = X, b = tf.transpose(Y), axes=1) # axes = 1 ( tf.transpose(Y).shape[1] )

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

In [218]:
# Check values of Y, reshape Y and tranposed Y
print("Normal Y:")
print(Y, "\n") # "\n" for newline

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, (2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


#### Changing the datatype of a tensor


In [220]:
B = tf.constant([1.7, 1.2])
C = tf.constant([3, 5])
B, C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 1.2], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 5])>)

In [221]:
B = tf.cast(x = B, dtype = tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 1.2], dtype=float16)>

In [222]:
C = tf.cast(x = C, dtype = tf.float32)
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 5.], dtype=float32)>

#### Absolute Value

In [226]:
D = tf.constant(np.arange(-10, -1, 1))
D

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2])>

In [228]:
D = tf.abs(x = D)
D

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([10,  9,  8,  7,  6,  5,  4,  3,  2])>

In [229]:
tf.abs(tf.constant([-2.25, 3.25]))

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

#### Finding the min, max, mean, sum (aggregation)

In [259]:
E = tf.constant(np.random.randint(low=0, high=100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([37, 34, 20, 58, 39, 70, 31, 18, 42, 76, 63, 52,  0, 40, 77, 88, 99,
       16, 95, 90, 53, 63, 30, 75, 70, 34, 33, 25,  3,  3, 11, 75, 30, 31,
       59, 79, 99, 51, 79, 60, 55, 84,  3, 16, 46,  4, 85, 88, 57, 44])>

In [244]:
E = tf.sort(E)
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([ 6,  7,  8,  9, 11, 14, 15, 15, 22, 22, 28, 31, 32, 33, 34, 36, 37,
       38, 38, 40, 41, 42, 42, 42, 43, 43, 47, 49, 53, 57, 58, 60, 61, 61,
       63, 64, 64, 65, 72, 75, 78, 79, 80, 84, 87, 88, 92, 98, 98, 99])>

In [249]:
print(f'Min Value In E {tf.reduce_min(E)}')
print(f'Max Value In E {tf.reduce_max(E)}')
print(f'Mean Value In E {tf.reduce_mean(E)}')
print(f'Sum of Value In E {tf.reduce_sum(E)}')

Min Value In E 6
Max Value In E 99
Mean Value In E 49
Sum of Value In E 2461


In [252]:
print(f'standard deviation Value In E {tf.math.reduce_std(tf.cast(E, tf.float32))}')

standard deviation Value In E 26.271116256713867


In [254]:
print(f'Variance Value In E {tf.math.reduce_variance(tf.cast(E, tf.float32))}')

Variance Value In E 690.1715698242188


#### Finding the positional maximum and minimum
 

In [267]:
tf.argmax(E).numpy()

16

In [266]:
E[16].numpy()

99

In [265]:
tf.argmin(E).numpy()

12

In [264]:
E[12].numpy()

0

#### Squeezing a tensor (removing all single dimensions)


In [271]:
G = tf.constant(np.random.randint(0, 100, 50), shape = (1, 1, 1, 50))
G.shape

TensorShape([1, 1, 1, 50])

In [275]:
tf.squeeze(G).shape , tf.squeeze(G).ndim

(TensorShape([50]), 1)

#### One-hot encoding


In [295]:
F = np.arange(0, 5, 1)
print(F)
tf_F = tf.Variable(F)
tf.one_hot(tf_F, depth=len(F), on_value='ON', off_value='OFF')

[0 1 2 3 4]


<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'ON', b'OFF', b'OFF', b'OFF', b'OFF'],
       [b'OFF', b'ON', b'OFF', b'OFF', b'OFF'],
       [b'OFF', b'OFF', b'ON', b'OFF', b'OFF'],
       [b'OFF', b'OFF', b'OFF', b'ON', b'OFF'],
       [b'OFF', b'OFF', b'OFF', b'OFF', b'ON']], dtype=object)>

In [288]:
# Create a list of indices
some_list = [0, 1, 2, 3]

# One hot encode them
tf.one_hot(some_list, depth=4, on_value='ON', off_value='OFF')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'ON', b'OFF', b'OFF', b'OFF'],
       [b'OFF', b'ON', b'OFF', b'OFF'],
       [b'OFF', b'OFF', b'ON', b'OFF'],
       [b'OFF', b'OFF', b'OFF', b'ON']], dtype=object)>

#### Squaring, log, square root


In [296]:
H = tf.constant(np.arange(1, 10))
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [299]:
res = tf.square(H)
res

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [302]:
tf.sqrt(tf.cast(res, tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [303]:
tf.math.log(tf.cast(res, tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 1.3862944, 2.1972246, 2.7725887, 3.218876 , 3.583519 ,
       3.8918204, 4.158883 , 4.394449 ], dtype=float32)>

#### Manipulating tf.Variable tensors

In [304]:
I = tf.Variable(np.arange(0, 5))
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([0, 1, 2, 3, 4])>

In [307]:
I.assign([10, 1, 2, 3, 100])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([ 10,   1,   2,   3, 100])>

In [308]:
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([ 10,   1,   2,   3, 100])>

In [309]:
I.assign_add([10, 10, 10, 10, 10])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([ 20,  11,  12,  13, 110])>

In [310]:
I.assign_sub([10, 10, 10, 10, 10])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([ 10,   1,   2,   3, 100])>

In [311]:
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([ 10,   1,   2,   3, 100])>

#### Tensors and NumPy

In [312]:
np.array(I)

array([ 10,   1,   2,   3, 100])

In [314]:
I.numpy()

array([ 10,   1,   2,   3, 100])

#### Using @tf.function

In [316]:
@tf.function
def function(x, y):
  return x ** 2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
function(x, y)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

#### Finding access to GPUs

In [321]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

### Exercises

#### Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().


In [324]:
t_scl = tf.constant(10)
t_vec = tf.constant([10, 20, 30])
t_mat = tf.constant([[1, 2], [3, 4]])

#### Find the shape, rank and size of the tensors you created in 1.


In [326]:
t_scl.shape, t_scl.ndim, tf.size(t_scl)

(TensorShape([]), 0, <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [327]:
t_vec.shape, t_vec.ndim, tf.size(t_vec)

(TensorShape([3]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=3>)

In [328]:
t_mat.shape, t_mat.ndim, tf.size(t_mat)

(TensorShape([2, 2]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=4>)

#### Create two tensors containing random values between 0 and 1 with shape [5, 300].


In [341]:
t1 = tf.random.uniform([5, 300], minval=0, maxval=1, seed=42)
t2 = tf.random.uniform([5, 300], minval=0, maxval=1, seed=42)

In [340]:
tf.reduce_min(t1), tf.reduce_max(t1)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.00015246868>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.99954736>)

In [342]:
tf.reduce_min(t2), tf.reduce_max(t2)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.00016844273>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.99952507>)

#### Multiply the two tensors you created in 3 using matrix multiplication.


In [344]:
t1 *3 , t2 *3

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.7143688 , 0.7297647 , 1.5155847 , ..., 1.6727597 , 2.0946229 ,
         0.356138  ],
        [0.7382884 , 1.8569291 , 2.5679002 , ..., 0.3564037 , 1.8816737 ,
         1.711171  ],
        [2.5221496 , 2.1224256 , 2.8150592 , ..., 0.7001785 , 2.1603518 ,
         1.8427913 ],
        [2.6163025 , 0.9960036 , 0.8335655 , ..., 1.1320299 , 2.718802  ,
         0.1737138 ],
        [1.761181  , 2.5487545 , 0.1593436 , ..., 0.21921408, 1.8565543 ,
         1.1532365 ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[1.6566786 , 2.2440472 , 2.572056  , ..., 0.0537411 , 1.190202  ,
         2.7168982 ],
        [1.9937285 , 0.29867435, 0.83128417, ..., 0.43139005, 0.00849438,
         0.48126805],
        [2.02928   , 2.8318934 , 2.5649493 , ..., 0.5722332 , 1.9645107 ,
         0.15373743],
        [1.7644336 , 1.3071431 , 2.3853614 , ..., 1.8798015 , 0.18877244,
         0.8775351 ],
        [2.94393

In [346]:
tf.multiply(t1, 3), tf.multiply(t2, 3)

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.7143688 , 0.7297647 , 1.5155847 , ..., 1.6727597 , 2.0946229 ,
         0.356138  ],
        [0.7382884 , 1.8569291 , 2.5679002 , ..., 0.3564037 , 1.8816737 ,
         1.711171  ],
        [2.5221496 , 2.1224256 , 2.8150592 , ..., 0.7001785 , 2.1603518 ,
         1.8427913 ],
        [2.6163025 , 0.9960036 , 0.8335655 , ..., 1.1320299 , 2.718802  ,
         0.1737138 ],
        [1.761181  , 2.5487545 , 0.1593436 , ..., 0.21921408, 1.8565543 ,
         1.1532365 ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[1.6566786 , 2.2440472 , 2.572056  , ..., 0.0537411 , 1.190202  ,
         2.7168982 ],
        [1.9937285 , 0.29867435, 0.83128417, ..., 0.43139005, 0.00849438,
         0.48126805],
        [2.02928   , 2.8318934 , 2.5649493 , ..., 0.5722332 , 1.9645107 ,
         0.15373743],
        [1.7644336 , 1.3071431 , 2.3853614 , ..., 1.8798015 , 0.18877244,
         0.8775351 ],
        [2.94393

#### Multiply the two tensors you created in 3 using dot product.

In [348]:
tf.matmul(t1, t2, transpose_a=True, transpose_b=False)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[1.9527406 , 1.5561132 , 1.9947951 , ..., 1.2795916 , 1.2429614 ,
        0.67514944],
       [2.0532153 , 1.3164194 , 1.6978825 , ..., 1.2078626 , 1.3673627 ,
        0.6292849 ],
       [1.6981049 , 1.4862261 , 1.7215858 , ..., 0.5334588 , 0.8838761 ,
        0.7352232 ],
       ...,
       [0.8383776 , 0.8360316 , 1.049161  , ..., 0.3743906 , 0.46563876,
        0.6615296 ],
       [2.4298153 , 1.8489958 , 2.435714  , ..., 1.3699133 , 1.3791205 ,
        1.1633705 ],
       [1.2714126 , 0.8684586 , 1.0341946 , ..., 0.586687  , 0.80975676,
        0.3272086 ]], dtype=float32)>

In [352]:
tf.tensordot(t1, t2, axes=0)

<tf.Tensor: shape=(5, 300, 5, 300), dtype=float32, numpy=
array([[[[1.31497726e-01, 1.78119719e-01, 2.04155177e-01, ...,
          4.26566275e-03, 9.44714695e-02, 2.15651929e-01],
         [1.58250839e-01, 2.37070713e-02, 6.59826100e-02, ...,
          3.42412889e-02, 6.74235343e-04, 3.82003225e-02],
         [1.61072701e-01, 2.24779591e-01, 2.03591093e-01, ...,
          4.54206169e-02, 1.55931681e-01, 1.22028030e-02],
         [1.40050709e-01, 1.03753589e-01, 1.89336419e-01, ...,
          1.49207950e-01, 1.49836829e-02, 6.96537495e-02],
         [2.33672649e-01, 7.29706213e-02, 1.25832975e-01, ...,
          2.16242597e-01, 2.20001638e-01, 4.94187102e-02]],

        [[1.34331733e-01, 1.81958497e-01, 2.08555073e-01, ...,
          4.35759500e-03, 9.65074897e-02, 2.20299602e-01],
         [1.61661416e-01, 2.42179986e-02, 6.74046502e-02, ...,
          3.49792466e-02, 6.88766304e-04, 3.90236042e-02],
         [1.64544091e-01, 2.29623988e-01, 2.07978830e-01, ...,
          4.63995114e-0

In [355]:
t1 @ tf.transpose(t2)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[79.030685, 74.670074, 75.07764 , 76.993385, 74.927216],
       [76.31954 , 73.21771 , 76.789154, 76.33877 , 73.77394 ],
       [81.67772 , 77.26543 , 81.0172  , 80.13854 , 75.490486],
       [83.385765, 78.209274, 81.091965, 80.96176 , 77.287224],
       [79.06482 , 77.02017 , 80.67801 , 83.15093 , 81.244705]],
      dtype=float32)>

#### Create a tensor with random values between 0 and 1 with shape [224, 224, 3]

In [357]:
t3 = tf.random.uniform(minval=0, maxval=1, shape=[224, 224, 3])
t3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.41944146, 0.60903394, 0.71607816],
        [0.858606  , 0.21797061, 0.9450581 ],
        [0.6909996 , 0.37632883, 0.7943243 ],
        ...,
        [0.8606609 , 0.5759177 , 0.47045183],
        [0.23429692, 0.9270003 , 0.7069298 ],
        [0.08124423, 0.74872947, 0.09985197]],

       [[0.01154613, 0.13842511, 0.09963918],
        [0.28309202, 0.47965026, 0.9722712 ],
        [0.03141236, 0.43445945, 0.88618433],
        ...,
        [0.442999  , 0.06895947, 0.13286304],
        [0.17474627, 0.19555521, 0.59531105],
        [0.24203098, 0.6120472 , 0.20349836]],

       [[0.21718132, 0.7927556 , 0.01837313],
        [0.19925857, 0.352324  , 0.16757154],
        [0.78222907, 0.61229587, 0.0013783 ],
        ...,
        [0.5328376 , 0.84509146, 0.00360966],
        [0.816821  , 0.8881712 , 0.65912855],
        [0.24904537, 0.23792958, 0.29897308]],

       ...,

       [[0.25376642, 0.89619505, 0.01317263],
        [0.61

#### Find the min and max values of the tensor you created in 


In [361]:
tf.reduce_min(t3).numpy(), tf.reduce_max(t3).numpy()

(1.0967255e-05, 0.99999917)

#### Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3]

In [364]:
t4 = tf.random.normal(shape=(1, 224, 224, 3))
t4, t4.shape

(<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
 array([[[[ 2.260564  , -0.6558232 , -0.46591297],
          [ 0.4690215 ,  1.026158  , -0.11631647],
          [ 0.18181528, -0.8653291 ,  0.34823856],
          ...,
          [-0.35340056, -0.8719383 , -0.9461825 ],
          [ 0.18835995, -0.98673624,  1.3287827 ],
          [-0.39012754, -0.3299349 , -0.48902255]],
 
         [[ 0.22111776, -0.3160937 ,  0.49287724],
          [ 0.7204182 , -2.4069533 ,  0.9773641 ],
          [ 1.3312837 ,  0.30342764, -0.6479191 ],
          ...,
          [ 1.8883672 ,  0.6237269 , -2.147329  ],
          [-0.7488012 , -0.17227246, -1.0924058 ],
          [-0.26205307,  1.2801088 ,  2.063088  ]],
 
         [[-0.28480947,  0.29857916,  1.7683946 ],
          [-0.1380807 , -0.21737191, -1.2778177 ],
          [-0.66610944,  2.6026862 , -0.43811208],
          ...,
          [ 0.39251983, -1.119603  ,  0.8051878 ],
          [-0.09851501, -1.6679809 , -1.5212544 ],
          [-1.0076456 ,

In [366]:
tf.squeeze(t4).shape

TensorShape([224, 224, 3])

#### Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value

In [373]:
t5 = tf.constant(np.random.random(10))
t5.shape

TensorShape([10])

In [374]:
t5

<tf.Tensor: shape=(10,), dtype=float64, numpy=
array([0.13512338, 0.73631264, 0.53125562, 0.18444603, 0.17353226,
       0.11001621, 0.30554796, 0.62743499, 0.37161748, 0.07290226])>

In [376]:
tf.argmax(t5).numpy()

1

In [377]:
tf.argmin(t5).numpy()

9

#### One-hot encode the tensor you created in

In [379]:
tf.size(t5).numpy()

10

In [383]:
t5

<tf.Tensor: shape=(10,), dtype=float64, numpy=
array([0.13512338, 0.73631264, 0.53125562, 0.18444603, 0.17353226,
       0.11001621, 0.30554796, 0.62743499, 0.37161748, 0.07290226])>

In [384]:
len(t5)

10

In [388]:
indicies = np.arange(0,10,1)
indicies
tf.one_hot(indicies, depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>